int signMask(void);
int mul5Sat(int x);
int clearByte(int x,int y);
int roundUp(int x);
int swapNibblePairs(int x);
int secondLowestZeroBit(int x);
int rotateRightBits(int x, int n);
int fractions(int x);
int overflowCalc(int x, int y, int z);
unsigned float_inv(int x);
unsigned float_i2f(int x);
int oddParity(int x);
int bitXor(int x, int y);
int negativePart(int x);
int isLargerOrEqual(int x, int y);
int bitCount(int x);
int bitReverse(int x);
int logicalShift(int x, int n);
unsigned float_half(unsigned uf);

int test_tconst(void);
int test_clearByte(int x,int y);
int test_roundUp(int x);
int test_swapNibblePairs(int x);
int test_secondLowestZeroBit(int x);
int test_rotateRightBits(int x, int n);
int test_fractions(int x);
int test_hdOverflow(int x,int y);
int test_overflowCalc(int x, int y, int z);
unsigned test_float_inv(int x);
unsigned test_float_i2f(int x);
int test_oddParity(int x);
int test_bitXor(int x, int y);
int test_signMask(void);
int test_negativePart(int x);
int test_isLargerOrEqual(int x, int y);
int test_bitCount(int x);
int test_bitReverse(int x);
int test_logicalShift(int x, int n);
unsigned test_float_half(unsigned uf);
int test_mul5Sat(int x);
